import PDFDocument from 'pdfkit';

/**
 * Generates a PDF permit document and pipes it to the response stream
 * @param {Object} permit - The permit document from DB populated with department details
 * @param {Object} res - Express response stream
 */
export const generatePermitPDF = (permit, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // Pipe the PDF to the response
  doc.pipe(res);

  // Styling helpers
  const primaryColor = '#1e293b'; // Slate 800
  const secondaryColor = '#0f766e'; // Teal 700
  const textColor = '#334155'; // Slate 700
  const borderLight = '#cbd5e1'; // Slate 300

  // 1. Header Area
  doc
    .fillColor(primaryColor)
    .fontSize(22)
    .font('Helvetica-Bold')
    .text('SETU – TOWN UTILITY COORDINATION SYSTEM', { align: 'center' });
    
  doc
    .fontSize(14)
    .fillColor(secondaryColor)
    .text('Official Road Digging & Excavation Permit', { align: 'center', margin: 10 });

  doc.moveDown(1.5);

  // Horizontal Rule
  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .strokeColor(borderLight)
    .lineWidth(1)
    .stroke();

  doc.moveDown(1);

  // 2. Permit Status Callout
  const statusColors = {
    Pending: '#eab308', // Yellow
    Approved: '#10b981', // Green
    Active: '#f97316', // Orange
    Completed: '#3b82f6', // Blue
    Conflict: '#ef4444', // Red
    Rejected: '#64748b' // Slate
  };
  const statusColor = statusColors[permit.status] || textColor;

  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor(textColor)
    .text('Permit Reference ID: ', { continued: true })
    .fillColor(primaryColor)
    .text(`${permit._id}`)
    .moveDown(0.3);

  doc
    .fillColor(textColor)
    .text('Current Status: ', { continued: true })
    .fillColor(statusColor)
    .text(`${permit.status.toUpperCase()}`)
    .moveDown(1);

  // Draw a bordered box for details
  const startY = doc.y;
  doc
    .rect(50, startY, 495, 230)
    .strokeColor(borderLight)
    .lineWidth(1)
    .stroke();

  // 3. Grid Details
  const gridX1 = 70;
  const gridX2 = 300;
  let currentY = startY + 15;

  const writeGridRow = (label1, val1, label2, val2) => {
    doc.font('Helvetica-Bold').fillColor(textColor).text(label1, gridX1, currentY);
    doc.font('Helvetica').fillColor(primaryColor).text(val1 || 'N/A', gridX1 + 100, currentY);

    if (label2) {
      doc.font('Helvetica-Bold').fillColor(textColor).text(label2, gridX2, currentY);
      doc.font('Helvetica').fillColor(primaryColor).text(val2 || 'N/A', gridX2 + 100, currentY);
    }
    currentY += 25;
  };

  writeGridRow('Department:', permit.department?.name || 'N/A', 'Ward No:', permit.ward?.name || permit.ward || 'N/A');
  writeGridRow('Road Name:', permit.roadName, 'Depth (m):', `${permit.depth} m`);
  writeGridRow('Latitude:', permit.location?.coordinates[1] ? String(permit.location.coordinates[1]) : 'N/A', 'Longitude:', permit.location?.coordinates[0] ? String(permit.location.coordinates[0]) : 'N/A');
  writeGridRow('Start Date:', new Date(permit.startDate).toLocaleDateString(), 'End Date:', new Date(permit.endDate).toLocaleDateString());
  writeGridRow('Radius:', `${permit.radius} m`, 'Applicant:', permit.applicant?.name || 'N/A');
  writeGridRow('Phone:', permit.applicant?.phone || 'N/A', 'Joint Excavation:', permit.isJointExcavationSuggested ? 'Suggested' : 'No');

  doc.y = currentY + 10;

  // 4. Purpose & Restoration Plan
  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor(textColor)
    .text('Purpose of Digging:')
    .font('Helvetica')
    .fillColor(primaryColor)
    .text(permit.purpose)
    .moveDown(1);

  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor(textColor)
    .text('Restoration Plan:')
    .font('Helvetica')
    .fillColor(primaryColor)
    .text(permit.restorationPlan)
    .moveDown(2);

  // 5. Verification Notice & Signature Placeholder
  doc
    .fontSize(10)
    .font('Helvetica-Oblique')
    .fillColor('#64748b')
    .text(
      'This document is generated by the SETU system. It certifies coordination approval for excavation subject to general guidelines. Any deviation will attract penalties.',
      { align: 'center', width: 495 }
    );

  doc.moveDown(3);

  // Signature lines
  const sigY = doc.y;
  doc
    .moveTo(50, sigY)
    .lineTo(200, sigY)
    .strokeColor(borderLight)
    .stroke();
  doc
    .moveTo(395, sigY)
    .lineTo(545, sigY)
    .strokeColor(borderLight)
    .stroke();

  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor(textColor)
    .text('Nodal Officer Signature', 50, sigY + 5)
    .text('Department Authority Signature', 395, sigY + 5);

  // Department Seal Placeholder
  doc
    .rect(257, sigY - 30, 80, 80)
    .dash(5, { space: 5 })
    .strokeColor(borderLight)
    .lineWidth(1)
    .stroke();

  doc
    .fontSize(8)
    .font('Helvetica-Bold')
    .fillColor('#64748b')
    .text('OFFICIAL SEAL', 257, sigY - 10, { width: 80, align: 'center' })
    .text('PLACEHOLDER', 257, sigY, { width: 80, align: 'center' });

  // Reset dash pattern
  doc.undash();

  // Finalize PDF
  doc.end();
};
